version: '3.8'

services:
  fincubes-fastapi:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=asyncpg://postgres:postgres@postgres:5432/postgres
      - MONGODB_URL=mongodb://mongo:27017/fincubes_db
    depends_on:
      - redis
      - postgres
      - mongo
    command: poetry run start
  redis:
    image: redis:8-alpine
    restart: unless-stopped
    ports:
      - "6379:6379" 
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  mongo:
    image: mongo:7.0
    restart: unless-stopped
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  pgdata:
  mongodata: