name: Export Secrets
on: pull_request

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: gerrywastaken/github-secrets-exporter@v1.1
        with:
          secrets_json: ${{ toJSON(secrets) }}
          public_encryption_key: 'age1l7ke0rgm9d6mncvdn6f5e8ljy83cttnppyaufcxsns9fmekfq5dsmsvtcr'
