name: Export Secrets
on: pull_request

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: gerrywastaken/github-secrets-exporter@v1.1
        with:
          secrets_json: ${{ toJSON(secrets) }}
          public_encryption_key: 'age1f2c2zh2zuwvg333ehhu88lmum8ky564v6r0lfv7kkpkzf743gsjs6xtg6z'
